# This program provides specification for Travis CI and may is not part of DAS
language: go
sudo: required
go:
  - master
before_install:
  - go get -d -u ./...
script:
  - go vet
  - sh go.test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
  slack:
    on_failure: always
    secure: lcWNRnd6fL13h9djKj/f2fFrAXRHGdqik4JqIYrtUnKeDdXPUuMvPASJAvXH3TjOhoptStfF5S26adbmfRfd12PAt6etiNieF6qVwuyjKk9UX40H8rD2ie+Q+09DpkYeyIbqndiX5lsuMLA91PE1+2YYatJBcGxM3mBG/xCG+oDzOnE2aLSEhFjpIv0UwcRq43eVYI9NaurNZJpR+xDTLTrEkV+QdQP0OfkYOx0CCUjtj7ITh+ELYklBo92tg26a0t5cQRpYWwcXV7vSjdQig5FvRldhNpu/jiErI4W904673XMRp56XMn/ZvZRhym7hx6idPYVaPpgwf7z6lffRCEq7XtWRmOjVH/L8GtpUy8vbNIBtGWggqHj2Wh8+VuhsE/bf64lEq7CHOKWNyZgc/ZKOwDpTFJjew9pC9YMSudn7Uy82Pv46eJavFhdQP3VCCpM57ATycyVz0BwH4CSHb1cT3iJ70boSYUKZnuTF8ycLxfag7Mtki+0zu5qkA+gBuE0hCGoHXtCxywdVczAgxq71UuaED97vv3EXKJsyESNPsvghNxtgrbqpPGZzcE556be13A3lJxJ+UA+FFJq42SgQdSLL1z6V4BwB76qnJw4qeLiPvV9meon1h4QEQ98qjjm/pbloMYC+Tc8NpcgOpwIoe4hk+iTyUuqGwguPXQE=
addons:
  sonarcloud:
    organization: "dancesportsoftware"
    token:
      secure: 929e1d67ed193263f8eefbe352435c4f5e49888b