# This program provides specification for deploying DAS on Google Cloud Platform 
# and is not part of DAS
runtime: go
env: flex

# replace environment variable in production
env_variables:
  POSTGRES_CONNECTION: "user=dasdev password=dAs!@#$1234 dbname=das host=/cloudsql/das-development-204605:us-central1:das-dev-02"
  HMAC_SIGNING_KEY: ""
  API_VERSION: "1.0"

# replace cloud sql connection in production
beta_settings:
  cloud_sql_instances: "das-development-204605:us-central1:das-dev-02"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.0
  disk_size_gb: 10
