CREATE TABLE IF NOT EXISTS DAS.ACCOUNT_ROLE (
  ID SERIAL NOT NULL PRIMARY KEY,
  ACCOUNT_TYPE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_TYPE(ID),
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(ACCOUNT_TYPE_ID, ACCOUNT_ID)
);

CREATE INDEX ON DAS.ACCOUNT_ROLE(ACCOUNT_TYPE_ID);
CREATE INDEX ON DAS.ACCOUNT_ROLE(ACCOUNT_ID);
