CREATE TABLE IF NOT EXISTS DAS.ORGANIZER_PROVISION_HISTORY (
  ID SERIAL NOT NULL PRIMARY KEY ,
  ORGANIZER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID),
  AMOUNT INTEGER NOT NULL DEFAULT 0,
  NOTE TEXT NOT NULL,
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX ON DAS.ORGANIZER_PROVISION_HISTORY(ORGANIZER_ID);