CREATE TABLE IF NOT EXISTS DAS.PARTNERSHIP_REQUEST_STATUS (
  ID SERIAL NOT NULL PRIMARY KEY ,
  CODE CHARACTER(1) NOT NULL UNIQUE,
  DESCRIPTION TEXT NOT NULL,
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO DAS.PARTNERSHIP_REQUEST_STATUS(CODE, DESCRIPTION) VALUES ('A',  'Accepted');
INSERT INTO DAS.PARTNERSHIP_REQUEST_STATUS(CODE, DESCRIPTION) VALUES ('P',  'Pending');
INSERT INTO DAS.PARTNERSHIP_REQUEST_STATUS(CODE, DESCRIPTION) VALUES ('D',  'Declined');