CREATE TABLE IF NOT EXISTS DAS.PARTNERSHIP_REQUEST_BLACKLIST_REASON (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR (24) UNIQUE NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO DAS.PARTNERSHIP_REQUEST_BLACKLIST_REASON(NAME, DESCRIPTION) VALUES ('SPAM','This user is sending me spam.');
INSERT INTO DAS.PARTNERSHIP_REQUEST_BLACKLIST_REASON(NAME, DESCRIPTION) VALUES ('HARASSMENT','This user is harassing me.');
INSERT INTO DAS.PARTNERSHIP_REQUEST_BLACKLIST_REASON(NAME, DESCRIPTION) VALUES ('THREATENING','This user is sending me hostile message.');