CREATE TABLE IF NOT EXISTS DAS.PROFILE_ATHLETE (
  ID SERIAL NOT NULL PRIMARY KEY,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  ACCOUNT_ROLE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.PROFILE_ATHLETE (ACCOUNT_ID);
CREATE INDEX ON DAS.PROFILE_ATHLETE (ACCOUNT_ROLE_ID);

CREATE TABLE IF NOT EXISTS DAS.PROFILE_ADJUDICATOR (
  ID SERIAL NOT NULL PRIMARY KEY,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  ACCOUNT_ROLE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.PROFILE_ADJUDICATOR (ACCOUNT_ID);
CREATE INDEX ON DAS.PROFILE_ADJUDICATOR (ACCOUNT_ROLE_ID);

CREATE TABLE IF NOT EXISTS DAS.PROFILE_SCRUTINEER (
  ID SERIAL NOT NULL PRIMARY KEY,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  ACCOUNT_ROLE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.PROFILE_SCRUTINEER (ACCOUNT_ID);
CREATE INDEX ON DAS.PROFILE_SCRUTINEER (ACCOUNT_ROLE_ID);

CREATE TABLE IF NOT EXISTS DAS.PROFILE_ORGANIZER (
  ID SERIAL NOT NULL PRIMARY KEY,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  ACCOUNT_ROLE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.PROFILE_ORGANIZER (ACCOUNT_ID);
CREATE INDEX ON DAS.PROFILE_ORGANIZER (ACCOUNT_ROLE_ID);

CREATE TABLE IF NOT EXISTS DAS.PROFILE_DECKCAPTAIN (
  ID SERIAL NOT NULL PRIMARY KEY,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  ACCOUNT_ROLE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.PROFILE_DECKCAPTAIN (ACCOUNT_ID);
CREATE INDEX ON DAS.PROFILE_DECKCAPTAIN (ACCOUNT_ROLE_ID);

CREATE TABLE IF NOT EXISTS DAS.PROFILE_EMCEE (
  ID SERIAL NOT NULL PRIMARY KEY,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  ACCOUNT_ROLE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.PROFILE_EMCEE (ACCOUNT_ID);
CREATE INDEX ON DAS.PROFILE_EMCEE (ACCOUNT_ROLE_ID);

CREATE TABLE IF NOT EXISTS DAS.PROFILE_ADMINISTRATOR (
  ID SERIAL NOT NULL PRIMARY KEY,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  ACCOUNT_ROLE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.PROFILE_ADMINISTRATOR (ACCOUNT_ID);
CREATE INDEX ON DAS.PROFILE_ADMINISTRATOR (ACCOUNT_ROLE_ID);