CREATE TABLE IF NOT EXISTS DAS.ACCOUNT_STATUS (
  ID SERIAL NOT NULL,
  NAME TEXT UNIQUE NOT NULL,
  ABBREVIATION CHARACTER (1) NOT NULL UNIQUE,
  DESCRIPTION TEXT,
  DATETIME_CREATED TIMESTAMP DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (ID)
);

INSERT INTO DAS.ACCOUNT_STATUS(NAME, ABBREVIATION, DESCRIPTION) VALUES ('Activated','A','Account is activated and verified and can be used');
INSERT INTO DAS.ACCOUNT_STATUS(NAME, ABBREVIATION, DESCRIPTION) VALUES ('Unverified','U','Account is created but not verified (email or phone number)');
INSERT INTO DAS.ACCOUNT_STATUS(NAME, ABBREVIATION, DESCRIPTION) VALUES ('Locked','L','Account is locked for security reasons');
INSERT INTO DAS.ACCOUNT_STATUS(NAME, ABBREVIATION, DESCRIPTION) VALUES ('Suspended','S','Account is suspended for violation of Terms of Services');