CREATE TABLE IF NOT EXISTS DAS.COMPETITION_PRODUCT (
  ID SERIAL NOT NULL  PRIMARY KEY ,
  COMPETITION_ID INTEGER NOT NULL REFERENCES DAS.COMPETITION(ID),
  PRODUCT_CATEGORY_ID INTEGER NOT NULL REFERENCES DAS.COMPETITION_PRODUCT_CATEGORY(ID),
  PRODUCT_TITLE VARCHAR(128) NOT NULL,
  PRODUCT_STATUS_ID INTEGER NOT NULL REFERENCES DAS.COMPETITION_PRODUCT_STATUS(ID),
  PRODUCT_DETAIL TEXT,
  PRODUCT_COST REAL NOT NULL CHECK (PRODUCT_COST >= 0),
  MAXIMUM_AMOUNT INTEGER CHECK (MAXIMUM_AMOUNT > 0),
  AVAILABLE_AMOUNT INTEGER CHECK (AVAILABLE_AMOUNT > 0),
  EFFECTIVE_START DATE NOT NULL DEFAULT NOW(),
  EFFECTIVE_END DATE NOT NULL DEFAULT NOW(),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);