CREATE TABLE IF NOT EXISTS DAS.COMPETITION (
  ID SERIAL NOT NULL PRIMARY KEY,
  FEDERATION_ID INTEGER NOT NULL REFERENCES DAS.FEDERATION (ID),
  NAME TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  CITY_ID INTEGER NOT NULL REFERENCES DAS.CITY (ID),
  STATE_ID INTEGER NOT NULL REFERENCES DAS.STATE(ID),
  COUNTRY_ID INTEGER NOT NULL REFERENCES DAS.COUNTRY(ID),
  DATETIME_START DATE NOT NULL,
  DATETIME_END DATE NOT NULL,
  CONTACT_NAME TEXT NOT NULL,
  CONTACT_PHONE TEXT NOT NULL,
  CONTACT_EMAIL TEXT NOT NULL,
  WEBSITE TEXT NOT NULL,
  STATUS_ID INTEGER NOT NULL REFERENCES DAS.COMPETITION_STATUS (ID),
  ATTENDANCE INT NOT NULL DEFAULT 0,
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.COMPETITION (NAME);
CREATE INDEX ON DAS.COMPETITION (CREATE_USER_ID);
CREATE INDEX ON DAS.COMPETITION (CITY_ID);
CREATE INDEX ON DAS.COMPETITION (STATE_ID);
CREATE INDEX ON DAS.COMPETITION (COUNTRY_ID);
CREATE INDEX ON DAS.COMPETITION (STATUS_ID);