CREATE TABLE IF NOT EXISTS DAS.COMPETITION_REPRESENTATION_PARTNERSHIP (
  ID SERIAL NOT NULL PRIMARY KEY,
  COMPETITION_ENTRY_ID INTEGER NOT NULL
    REFERENCES DAS.COMPETITION_ENTRY_PARTNERSHIP(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  STUDIO_ID INTEGER REFERENCES DAS.STUDIO(ID), -- competitor representation
  SCHOOL_ID INTEGER REFERENCES DAS.SCHOOL(ID), -- competitor representation
  STATE_ID INTEGER REFERENCES DAS.STATE(ID), -- competitor representation
  COUNTRY_ID INTEGER REFERENCES DAS.COUNTRY(ID), -- competitor representation
  CREATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (COMPETITION_ENTRY_ID)
);

CREATE INDEX ON DAS.COMPETITION_REPRESENTATION_PARTNERSHIP (STUDIO_ID);
CREATE INDEX ON DAS.COMPETITION_REPRESENTATION_PARTNERSHIP (SCHOOL_ID);
CREATE INDEX ON DAS.COMPETITION_REPRESENTATION_PARTNERSHIP (STATE_ID);
CREATE INDEX ON DAS.COMPETITION_REPRESENTATION_PARTNERSHIP (COUNTRY_ID);