CREATE TABLE IF NOT EXISTS DAS.COMPETITION_PRODUCT_ORDER (
  ID SERIAL NOT NULL  PRIMARY KEY ,
  COMPETITION_ID INTEGER NOT NULL REFERENCES DAS.COMPETITION(ID),
  PRODUCT_ID INTEGER NOT NULL REFERENCES DAS.COMPETITION_PRODUCT(ID),
  USER_ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  QUANTITY INTEGER NOT NULL CHECK (QUANTITY > 0),
  TOTAL_COST REAL NOT NULL CHECK (TOTAL_COST > 0),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);