CREATE TABLE IF NOT EXISTS DAS.DANCE (
  ID SERIAL NOT NULL PRIMARY KEY ,
  NAME VARCHAR(24) NOT NULL,
  ABBREVIATION VARCHAR (2) NOT NULL,
  DESCRIPTION TEXT,
  STYLE_ID INTEGER REFERENCES DAS.STYLE(ID),
  CREATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (NAME, STYLE_ID)
);

INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Waltz', 'W', 'International Waltz', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Standard'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Tango', 'T', 'International Tango', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Standard'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Viennese Waltz', 'V', 'International Viennese Waltz', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Standard'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Foxtrot', 'F', 'International Foxtrot', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Standard'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Quickstep', 'Q', 'International Quickstep', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Standard'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Cha Cha', 'C', 'International Cha Cha', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Latin'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Samba', 'S', 'International Samba', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Latin'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Rumba', 'R', 'International Rumba', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Latin'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Paso Doble', 'P', 'International Paso Doble', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Latin'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Jive', 'J', 'International Jive', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Latin'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Waltz', 'W', 'American Waltz', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Smooth'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Tango', 'T', 'American Tango', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Smooth'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Foxtrot', 'F', 'American Foxtrot', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Smooth'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Viennese Waltz', 'V', 'American Viennese Waltz', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Smooth'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Cha Cha', 'C', 'American Cha Cha', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Rhythm'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Rumba', 'R', 'American Rumba', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Rhythm'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Swing', 'S', 'American Swing', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Rhythm'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Bolero', 'B', 'American Bolero', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Rhythm'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Mambo', 'M', 'American Mambo', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Rhythm'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Waltz', 'W', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Tango', 'T', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Viennese Waltz', 'V', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Foxtrot', 'F', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Quickstep', 'Q', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Cha Cha', 'C', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Samba', 'S', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Rumba', 'R', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Paso Doble', 'P', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Jive', 'J', 'International Ten-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Intl. Ten Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Waltz', 'W', 'American Nine-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Tango', 'T', 'Am. Nine Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Foxtrot', 'F', 'American Nine-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Viennese Waltz', 'V', 'American Nine-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Cha Cha', 'C', 'American Nine-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Rumba', 'R', 'American Nine-Dance,', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Swing', 'S', 'American Nine-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Bolero', 'B', 'American Nine-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));
INSERT INTO DAS.DANCE(NAME, ABBREVIATION, DESCRIPTION, STYLE_ID)
VALUES ('Mambo', 'M', 'American Nine-Dance', (SELECT S.ID FROM DAS.STYLE S WHERE S.NAME = 'Am. Nine Dance'));