-- Event Entry for Athletes
CREATE TABLE IF NOT EXISTS DAS.EVENT_ENTRY_ATHLETE (
  ID SERIAL NOT NULL PRIMARY KEY,
  ATHLETE_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID) ON DELETE CASCADE,
  COMPETITION_ID INTEGER NOT NULL REFERENCES DAS.COMPETITION (ID) ON DELETE CASCADE,
  EVENT_ID INTEGER NOT NULL REFERENCES DAS.EVENT(ID) ON DELETE CASCADE,
  CHECKIN_IND BOOLEAN NOT NULL DEFAULT FALSE,
  CHECKIN_DATETIME TIMESTAMP DEFAULT NOW(),
  PLACEMENT INTEGER NOT NULL DEFAULT 0,
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Event Entry for Partnerships
CREATE TABLE IF NOT EXISTS DAS.EVENT_ENTRY_PARTNERSHIP (
  ID SERIAL NOT NULL PRIMARY KEY ,
  EVENT_ID INTEGER NOT NULL REFERENCES DAS.EVENT(ID) ON DELETE CASCADE,
  PARTNERSHIP_ID INTEGER NOT NULL REFERENCES DAS.PARTNERSHIP (ID) ON DELETE CASCADE,
  LEADTAG INTEGER NOT NULL DEFAULT 0,
  PLACEMENT INTEGER NOT NULL DEFAULT 0,
  CHECKIN_IND BOOLEAN NOT NULL DEFAULT FALSE, -- if user is not checked in, this is not count as entry
  CHECKIN_DATETIME TIMESTAMP DEFAULT NOW(),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (EVENT_ID, PARTNERSHIP_ID)
);

CREATE INDEX ON DAS.EVENT_ENTRY_PARTNERSHIP (EVENT_ID);
CREATE INDEX ON DAS.EVENT_ENTRY_PARTNERSHIP (PARTNERSHIP_ID);
CREATE INDEX ON DAS.EVENT_ENTRY_PARTNERSHIP (CREATE_USER_ID);

-- Event Entry for Adjudicator
CREATE TABLE IF NOT EXISTS DAS.EVENT_ENTRY_ADJUDICATOR (
  ID SERIAL NOT NULL PRIMARY KEY,
  EVENT_ID INTEGER NOT NULL REFERENCES DAS.EVENT(ID),
  ADJUDICATOR_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  CHECKIN_IND BOOLEAN NOT NULL DEFAULT FALSE, -- if user is not checked in, this is not count as entry
  CHECKIN_DATETIME TIMESTAMP,
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (EVENT_ID, ADJUDICATOR_ID)
);

CREATE INDEX ON DAS.EVENT_ENTRY_ADJUDICATOR (EVENT_ID);
CREATE INDEX ON DAS.EVENT_ENTRY_ADJUDICATOR (ADJUDICATOR_ID);