CREATE TABLE IF NOT EXISTS DAS.EVENT_STATUS (
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL UNIQUE,
  ABBREVIATION CHARACTER(1) NOT NULL UNIQUE,
  DESCRIPTION TEXT,
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO DAS.EVENT_STATUS (NAME, ABBREVIATION) VALUES ('Draft','F');
INSERT INTO DAS.EVENT_STATUS (NAME, ABBREVIATION) VALUES ('Open','P');
INSERT INTO DAS.EVENT_STATUS (NAME, ABBREVIATION) VALUES ('Running','R');
INSERT INTO DAS.EVENT_STATUS (NAME, ABBREVIATION) VALUES ('Closed','C');
INSERT INTO DAS.EVENT_STATUS (NAME, ABBREVIATION) VALUES ('Canceled','L');