-- one competition may host events of different federations
CREATE TABLE IF NOT EXISTS DAS.EVENT(
  ID SERIAL PRIMARY KEY NOT NULL,
  COMPETITION_ID INTEGER NOT NULL REFERENCES DAS.COMPETITION(ID),
  CATEGORY_ID INTEGER NOT NULL REFERENCES DAS.EVENT_CATEGORY(ID),
  FEDERATION_ID INTEGER NOT NULL REFERENCES DAS.FEDERATION (ID),
  DIVISION_ID INTEGER NOT NULL REFERENCES DAS.DIVISION(ID),
  AGE_ID INTEGER REFERENCES DAS.AGE (ID),
  PROFICIENCY_ID INTEGER REFERENCES DAS.PROFICIENCY (ID),
  STYLE_ID INTEGER NOT NULL REFERENCES DAS.STYLE(ID),
  DESCRIPTION TEXT,
  EVENT_STATUS_ID INTEGER NOT NULL REFERENCES DAS.EVENT_STATUS(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES  DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES  DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.EVENT (COMPETITION_ID);
CREATE INDEX ON DAS.EVENT (CREATE_USER_ID);

