CREATE TABLE IF NOT EXISTS DAS.ORGANIZER_PROVISION (
  ID SERIAL NOT NULL PRIMARY KEY ,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID) UNIQUE,
  ORGANIZER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE(ID) UNIQUE,
  HOSTED INTEGER NOT NULL DEFAULT 0,
  AVAILABLE INTEGER NOT NULL DEFAULT 0,
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.ORGANIZER_PROVISION (ACCOUNT_ID);
CREATE INDEX ON DAS.ORGANIZER_PROVISION (ORGANIZER_ID);