CREATE TABLE IF NOT EXISTS DAS.PARTNERSHIP_REQUEST_BLACKLIST (
  ID SERIAL NOT NULL PRIMARY KEY ,
  REPORTER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  BLOCKED_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  BLACKLIST_REASON_ID INTEGER NOT NULL REFERENCES DAS.PARTNERSHIP_REQUEST_BLACKLIST_REASON (ID),
  DETAIL TEXT,
  WHITELISTED_IND BOOLEAN,
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);