CREATE TABLE IF NOT EXISTS DAS.PARTNERSHIP (
  ID SERIAL NOT NULL PRIMARY KEY ,
  LEAD_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE (ID),
  FOLLOW_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE (ID),
  SAMESEX_IND BOOLEAN NOT NULL DEFAULT FALSE,
  FAVORITE_BY_LEAD BOOLEAN NOT NULL DEFAULT FALSE,
  FAVORITE_BY_FOLLOW BOOLEAN NOT NULL DEFAULT FALSE,
  COMPETITIONS_ATTENDED INTEGER NOT NULL DEFAULT 0,
  EVENTS_ATTENDED INTEGER NOT NULL DEFAULT 0,
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (LEAD_ID, FOLLOW_ID)
);

CREATE INDEX ON DAS.PARTNERSHIP(LEAD_ID);
CREATE INDEX ON DAS.PARTNERSHIP(FOLLOW_ID);
CREATE INDEX ON DAS.PARTNERSHIP(SAMESEX_IND);

CREATE OR REPLACE VIEW DAS.PARTNERSHIP_VIEW AS
  SELECT
         DAS.PARTNERSHIP.ID,
         LEAD.ID AS LEAD_ID,
         LEAD.FIRST_NAME AS LEAD_FIRST_NAME,
         LEAD.LAST_NAME AS LEAD_LAST_NAME,
         FOLLOW.ID AS FOLLOW_ID,
         FOLLOW.FIRST_NAME AS FOLLOW_FIRST_NAME,
         FOLLOW.LAST_NAME AS FOLLOW_LAST_NAME
  FROM DAS.PARTNERSHIP
  INNER JOIN DAS.ACCOUNT LEAD ON LEAD.ID = DAS.PARTNERSHIP.LEAD_ID
  INNER JOIN DAS.ACCOUNT FOLLOW ON FOLLOW.ID = DAS.PARTNERSHIP.FOLLOW_ID;
