CREATE TABLE IF NOT EXISTS DAS.PARTNERSHIP_REQUEST (
  ID SERIAL NOT NULL PRIMARY KEY ,
  SENDER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  RECIPIENT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  SENDER_ROLE INTEGER NOT NULL REFERENCES DAS.PARTNERSHIP_ROLE (ID),
  RECIPIENT_ROLE INTEGER NOT NULL REFERENCES DAS.PARTNERSHIP_ROLE (ID),
  MESSAGE TEXT,
  REQUEST_STATUS INTEGER NOT NULL REFERENCES DAS.PARTNERSHIP_REQUEST_STATUS(ID),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOt NULL DEFAULT NOW (),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.PARTNERSHIP_REQUEST (SENDER_ID);
CREATE INDEX ON DAS.PARTNERSHIP_REQUEST (RECIPIENT_ID);
CREATE INDEX ON DAS.PARTNERSHIP_REQUEST (CREATE_USER_ID);
CREATE INDEX ON DAS.PARTNERSHIP_REQUEST (UPDATE_USER_ID);
CREATE INDEX ON DAS.PARTNERSHIP_REQUEST (REQUEST_STATUS);