CREATE TABLE IF NOT EXISTS DAS.PARTNERSHIP_ROLE (
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR (16) NOT NULL UNIQUE,
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO DAS.PARTNERSHIP_ROLE(NAME) VALUES ('Follow');
INSERT INTO DAS.PARTNERSHIP_ROLE(NAME) VALUES ('Lead');