CREATE TABLE IF NOT EXISTS DAS.PARTNERSHIP (
  ID SERIAL NOT NULL PRIMARY KEY ,
  LEAD_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE (ID),
  FOLLOW_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT_ROLE (ID),
  SAMESEX_IND BOOLEAN NOT NULL DEFAULT FALSE,
  FAVORITE_BY_LEAD BOOLEAN NOT NULL DEFAULT FALSE,
  FAVORITE_BY_FOLLOW BOOLEAN NOT NULL DEFAULT FALSE,
  COMPETITIONS_ATTENDED INTEGER NOT NULL DEFAULT 0,
  EVENTS_ATTENDED INTEGER NOT NULL DEFAULT 0,
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (LEAD_ID, FOLLOW_ID)
);

CREATE INDEX ON DAS.PARTNERSHIP(LEAD_ID);
CREATE INDEX ON DAS.PARTNERSHIP(FOLLOW_ID);
CREATE INDEX ON DAS.PARTNERSHIP(SAMESEX_IND);