CREATE TABLE IF NOT EXISTS DAS.PROFICIENCY (
  ID SERIAL NOT NULL PRIMARY KEY ,
  NAME VARCHAR(24) NOT NULL,
  DIVISION_ID INTEGER NOT NULL REFERENCES DAS.DIVISION(ID),
  DESCRIPTION TEXT,
  CREATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(NAME, DIVISION_ID)
);

INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Newcomer',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'COL' AND F.ABBREVIATION = 'COL'), 'Collegiate Newcomer');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Bronze',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'COL' AND F.ABBREVIATION = 'COL'), 'Collegiate Bronze');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Silver',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'COL' AND F.ABBREVIATION = 'COL'), 'Collegiate Silver');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Gold',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'COL' AND F.ABBREVIATION = 'COL'), 'Collegiate Gold');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Syllabus',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'COL' AND F.ABBREVIATION = 'COL'), 'Collegiate Syllabus');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Novice',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'COL' AND F.ABBREVIATION = 'COL'), 'Collegiate Novice');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Pre-Championship',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'COL' AND F.ABBREVIATION = 'COL'), 'Collegiate Pre-Championship');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Championship',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'COL' AND F.ABBREVIATION = 'COL'), 'Collegiate Championship');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Newcomer',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'IND'), 'Independent Amateur Newcomer');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Bronze',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'IND'), 'Independent Amateur Bronze');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Silver',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'IND'), 'Independent Amateur Silver');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Gold',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'IND'), 'Independent Amateur Gold');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Novice',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'IND'), 'Independent Amateur Novice');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Pre-Championship',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'IND'), 'Independent Amateur Pre-Championship');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Championship',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'IND'), 'Independent Amateur Championship');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Pre Bronze',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Amateur Pre-Bronze');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Bronze',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Amateur Bronze');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Silver',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Amateur Silver');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Gold',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Amateur Gold');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Novice',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Amateur Novice');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Pre-Championship',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Amateur Pre-Championship');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Championship',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Amateur Championship');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Syllabus',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'AM' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Amateur Syllabus');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Pre Bronze',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'TS' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Teacher-Student Pre Bronze');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Full Bronze',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'TS' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Teacher-Student Full Bronze');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Intermediate Silver',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'TS' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Teacher-Student Intermediate Silver');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Full Silver',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'TS' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Teacher-Student Full Silver');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Intermediate Gold',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'TS' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Teacher-Student Intermediate Gold');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Full Gold',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'TS' AND F.ABBREVIATION = 'USA DANCE'), 'USA DANCE Teacher-Student Full Gold');
INSERT INTO DAS.PROFICIENCY (NAME, DIVISION_ID, DESCRIPTION)
VALUES ('Open Championship',
        (SELECT D.ID FROM DAS.DIVISION D
          JOIN DAS.FEDERATION F ON D.FEDERATION_ID = F.ID
        WHERE D.ABBREVIATION = 'WDSF' AND F.ABBREVIATION = 'WDSF'), 'WDSF Open Championship');