CREATE TABLE IF NOT EXISTS DAS.PROFILE_COMPETITOR_BASIC (
  PROFILE_ID SERIAL NOT NULL UNIQUE PRIMARY KEY,
  USER_ID INTEGER NOT NULL REFERENCES DAS.USER_ACCOUNT(USER_ACCOUNT_ID) UNIQUE, -- one dancer must have only one profile
  HEIGHT INTEGER NOT NULL DEFAULT 0,
  CREATE_USER INTEGER NOT NULL REFERENCES DAS.USER_ACCOUNT(USER_ACCOUNT_ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW,
  UPDATE_USER INTEGER NOT NULL REFERENCES DAS.USER_ACCOUNT(USER_ACCOUNT_ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW
);