-- Partnership Round Entry
CREATE TABLE IF NOT EXISTS DAS.ROUND_ENTRY_PARTNERSHIP (
    ID SERIAL NOT NULL PRIMARY KEY,
    ROUND_ID INTEGER NOT NULL REFERENCES DAS.ROUND (ID),
    PARTNERSHIP_ID INTEGER NOT NULL REFERENCES DAS.PARTNERSHIP (ID),
    CHECKIN_IND BOOLEAN NOT NULL DEFAULT FALSE, -- if user is not checked in, this is not count as entry
    CHECKIN_DATETIME TIMESTAMP,
    CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
    DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
    DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (ROUND_ID, PARTNERSHIP_ID)
);

CREATE INDEX ON DAS.ROUND_ENTRY_PARTNERSHIP (ROUND_ID);
CREATE INDEX ON DAS.ROUND_ENTRY_PARTNERSHIP (PARTNERSHIP_ID);

-- Adjudicator Round Entry
CREATE TABLE IF NOT EXISTS DAS.ROUND_ENTRY_ADJUDICATOR (
    ID SERIAL NOT NULL PRIMARY KEY ,
    ROUND_ID INTEGER NOT NULL REFERENCES DAS.ROUND (ID),
    ADJUDICATOR_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
    CHECKIN_IND BOOLEAN NOT NULL DEFAULT FALSE, -- if user is not checked in, this is not count as entry
    CHECKIN_DATETIME TIMESTAMP,
    CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
    DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
    DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (ROUND_ID, ADJUDICATOR_ID)
);

CREATE INDEX ON DAS.ROUND_ENTRY_ADJUDICATOR (ROUND_ID);
CREATE INDEX ON DAS.ROUND_ENTRY_ADJUDICATOR (ADJUDICATOR_ID);