-- Round of each event
CREATE TABLE IF NOT EXISTS DAS.ROUND (
    ID SERIAL NOT NULL PRIMARY KEY,
    EVENT_ID INTEGER NOT NULL REFERENCES DAS.EVENT (ID),
    ROUND_ORDER SERIAL NOT NULL,
    CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
    DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
    DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UNIQUE (EVENT_ID, ROUND_ORDER)
);
