-- create table das.school
CREATE TABLE IF NOT EXISTS DAS.SCHOOL (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(80) NOT NULL,
  CITY_ID INTEGER NOT NULL REFERENCES DAS.CITY(ID),
  CREATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(NAME, CITY_ID)
);

CREATE INDEX ON DAS.SCHOOL (CITY_ID);

INSERT INTO DAS.SCHOOL (NAME, CITY_ID) VALUES
  ('University of Wisconsin-Madison',(SELECT C.ID FROM DAS.CITY C JOIN DAS.STATE S ON C.STATE_ID = S.ID JOIN DAS.COUNTRY T ON S.COUNTRY_ID = T.ID
  WHERE C.NAME = 'Madison' AND S.ABBREVIATION = 'WI' AND T.ABBREVIATION = 'USA'));