-- Create table das.state
-- Indexed Columns:
CREATE TABLE IF NOT EXISTS DAS.STATE (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL,
  ABBREVIATION VARCHAR (8),
  COUNTRY_ID INTEGER NOT NULL REFERENCES DAS.COUNTRY (ID),
  CREATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (NAME, COUNTRY_ID)
);

CREATE INDEX ON DAS.STATE (COUNTRY_ID);

INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Alabama', 'AL', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Alaska', 'AK', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Arizona', 'AZ', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Arkansas', 'AR', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('California', 'CA', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Colorado', 'CO', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Connecticut', 'CT', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('District of Columbia','DC',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Delaware','DE',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Florida','FL',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Georgia','GA',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Hawaii','HI',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Idaho','ID',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Illinois','IL',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Indiana','IN',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Iowa','IA',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Kansas','KS',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Kentucky','KY',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Louisiana','LA',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Maine','ME', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Maryland','MD',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Massachusetts','MA',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Michigan','MI',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Minnesota','MN',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Mississippi','MS',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Missouri','MO',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Montana','MT',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Nebraska','NE',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Nevada','NV',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('New Hampshire','NH',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('New Jersey','NJ',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('New Mexico','NM',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('New York','NY',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('North Carolina','NC',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('North Dakota','ND',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Ohio','OH',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Oklahoma','OK',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Oregon','OR',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Pennsylvania','PA',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Puerto Rico','PR',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Rhode Island','RI',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('South Carolina','SC',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('South Dakota','SD',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Tennessee','TN',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Texas','TX',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Utah','UT',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Vermont','VT',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Virginia','VA',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Washington','WA',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('West Virginia','WV',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Wisconsin','WI',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Wyoming','WY',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'USA'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Alberta','AB',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('British Columbia','BC',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Manitoba','MB',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('New Brunswick','NB',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Newfoundland and Labrador','NL',  (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Northwest Territories','NT',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Nova Scotia','NS', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Nunavut','NU',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Prince Edward Island','PE', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Ontario','ON',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Quebec','QC', (SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Saskatchewan','SK',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));
INSERT INTO DAS.STATE (NAME, ABBREVIATION, COUNTRY_ID) VALUES('Yukon','YT',(SELECT C.ID FROM DAS.COUNTRY C WHERE C.ABBREVIATION = 'CAN'));