CREATE TABLE IF NOT EXISTS DAS.STYLE (
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(24) NOT NULL UNIQUE,
  DESCRIPTION TEXT,
  CREATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO DAS.STYLE (NAME, DESCRIPTION) VALUES ('Standard','International Standard');
INSERT INTO DAS.STYLE (NAME, DESCRIPTION) VALUES ('Latin','International Latin');
INSERT INTO DAS.STYLE (NAME, DESCRIPTION) VALUES ('Smooth','American Smooth');
INSERT INTO DAS.STYLE (NAME, DESCRIPTION) VALUES ('Rhythm','American Rhythm');
INSERT INTO DAS.STYLE (NAME, DESCRIPTION) VALUES ('Intl. Ten Dance','International Ten-Dance');
INSERT INTO DAS.STYLE (NAME, DESCRIPTION) VALUES ('Am. Nine Dance','American Nine-Dance');