CREATE TABLE IF NOT EXISTS DAS.USER_PREFERENCE (
  ID SERIAL PRIMARY KEY NOT NULL,
  ACCOUNT_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT (ID),
  DEFAULT_ROLE INTEGER NOT NULl REFERENCES DAS.ACCOUNT_TYPE (ID),
  CREATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER REFERENCES DAS.ACCOUNT (ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX ON DAS.USER_PREFERENCE (ACCOUNT_ID);
CREATE INDEX ON DAS.USER_PREFERENCE (DEFAULT_ROLE);
CREATE INDEX ON DAS.USER_PREFERENCE (CREATE_USER_ID);