package common

const (
	PRIMARY_KEY          = "ID"
	COL_NAME             = "NAME"
	COL_ACCOUNT_ID       = "ACCOUNT_ID"
	COL_UUID             = "UUID"
	COL_ABBREVIATION     = "ABBREVIATION"
	COL_DESCRIPTION      = "DESCRIPTION"
	COL_NOTE             = "NOTE"
	COL_DATETIME_CREATED = "DATETIME_CREATED"
	COL_DATETIME_UPDATED = "DATETIME_UPDATED"
	COL_CREATE_USER_ID   = "CREATE_USER_ID"
	COL_UPDATE_USER_ID   = "UPDATE_USER_ID"

	COL_COMPETITION_ID = "COMPETITION_ID"
	COL_EVENT_ID       = "EVENT_ID"

	COL_COUNTRY_ID     = "COUNTRY_ID"
	COL_STATE_ID       = "STATE_ID"
	COL_CITY_ID        = "CITY_ID"
	COL_ADDRESS        = "ADDRESS"
	COL_WEBSITE        = "WEBSITE"
	COL_FEDERATION_ID  = "FEDERATION_ID"
	COL_DIVISION_ID    = "DIVISION_ID"
	COL_AGE_ID         = "AGE_ID"
	COL_PROFICIENCY_ID = "PROFICIENCY_ID"
	COL_STYLE_ID       = "STYLE_ID"
	COL_DANCE_ID       = "DANCE_ID"

	COL_PARTNERSHIP_ID = "PARTNERSHIP_ID"
)
