package common

const (
	ColumnPrimaryKey      = "ID"
	COL_NAME              = "NAME"
	ColumnAccountID       = "ACCOUNT_ID"
	ColumnAccountTypeID   = "ACCOUNT_TYPE_ID"
	ColumnUID             = "UID"
	ColumnAbbreviation    = "ABBREVIATION"
	COL_DESCRIPTION       = "DESCRIPTION"
	COL_NOTE              = "NOTE"
	ColumnDateTimeCreated = "DATETIME_CREATED"
	ColumnDateTimeUpdated = "DATETIME_UPDATED"
	ColumnCreateUserID    = "CREATE_USER_ID"
	ColumnUpdateUserID    = "UPDATE_USER_ID"

	ColumnStatusID     = "STATUS_ID"
	COL_COMPETITION_ID = "COMPETITION_ID"
	COL_EVENT_ID       = "EVENT_ID"

	COL_PLACEMENT = "PLACEMENT"

	COL_COUNTRY_ID     = "COUNTRY_ID"
	COL_STATE_ID       = "STATE_ID"
	COL_CITY_ID        = "CITY_ID"
	COL_ADDRESS        = "ADDRESS"
	COL_WEBSITE        = "WEBSITE"
	COL_FEDERATION_ID  = "FEDERATION_ID"
	COL_DIVISION_ID    = "DIVISION_ID"
	COL_AGE_ID         = "AGE_ID"
	COL_PROFICIENCY_ID = "PROFICIENCY_ID"
	COL_STYLE_ID       = "STYLE_ID"
	COL_DANCE_ID       = "DANCE_ID"

	COL_ATHLETE_ID     = "ATHLETE_ID"
	COL_PARTNERSHIP_ID = "PARTNERSHIP_ID"
	COL_ADJUDICATOR_ID = "ADJUDICATOR_ID"
	COL_SCRUTINEER_ID  = "SCRUTINEER_ID"
	COL_ORGANIZER_ID   = "ORGANIZER_ID"

	COL_DATETIME_STARTED = "DATETIME_STARTED"
	COL_DATETIME_ENDED   = "DATETIME_ENDED"
)
