SELECT DISTINCT
  CE.COMPETITION_ID,
  ECBE.PARTNERSHIP_ID,
  CR.COUNTRY_ID,
  CR.STATE_ID,
  CR.SCHOOL_ID,
  CR.STUDIO_ID
FROM DAS.COMPETITION_ENTRY CE
JOIN DAS.COMPETITION_REPRESENTATION CR ON CR.COMPETITION_ENTRY_ID = CE.ID
  JOIN DAS.EVENT E ON E.COMPETITION_ID = CE.COMPETITION_ID
  JOIN DAS.EVENT_COMPETITIVE_BALLROOM ECB ON ECB.EVENT_ID = E.ID
  JOIN DAS.EVENT_COMPETITIVE_BALLROOM_ENTRY ECBE ON ECBE.COMPETITIVE_BALLROOM_EVENT_ID = ECB.ID
    WHERE CE.COMPETITION_ID = 1 AND ECBE.PARTNERSHIP_ID = 1;

SELECT
  ECBE.COMPETITIVE_BALLROOM_EVENT_ID
FROM DAS.EVENT_COMPETITIVE_BALLROOM_ENTRY ECBE
JOIN DAS.EVENT_COMPETITIVE_BALLROOM ECB ON ECBE.COMPETITIVE_BALLROOM_EVENT_ID = ECB.ID
JOIN DAS.EVENT E ON ECB.EVENT_ID = E.ID
WHERE ECBE.PARTNERSHIP_ID = 1
AND E.COMPETITION_ID = 1;


-- find attendance
SELECT COUNT(CE.ID) FROM DAS.COMPETITION_ENTRY CE WHERE CE.COMPETITION_ID = 1;

-- find unique federation
SELECT DISTINCT ECB.FEDERATION_ID, F.NAME FROM DAS.EVENT_COMPETITIVE_BALLROOM ECB JOIN DAS.FEDERATION F
				ON ECB.FEDERATION_ID = F.ID JOIN DAS.EVENT E ON E.ID = ECB.EVENT_ID WHERE E.COMPETITION_ID = 1;

-- get entry list
SELECT ECBE.ID, ECB.ID, E.ID, C.ID, P.ID, P.LEAD_ID, P.FOLLOW_ID, AL.LAST_NAME, AL.FIRST_NAME,
  AF.LAST_NAME, AF.FIRST_NAME
FROM DAS.EVENT_COMPETITIVE_BALLROOM_ENTRY ECBE
JOIN DAS.EVENT_COMPETITIVE_BALLROOM ECB ON ECBE.COMPETITIVE_BALLROOM_EVENT_ID = ECB.ID
JOIN DAS.EVENT E ON ECB.EVENT_ID = E.ID
JOIN DAS.COMPETITION C ON E.COMPETITION_ID = C.ID
JOIN DAS.PARTNERSHIP P ON ECBE.PARTNERSHIP_ID = P.ID
JOIN DAS.ACCOUNT AL ON AL.ID = P.LEAD_ID
JOIN DAS.ACCOUNT AF ON AF.ID = P.FOLLOW_ID
WHERE E.COMPETITION_ID = 1;


SELECT ECBE.COMPETITIVE_BALLROOM_EVENT_ID
FROM DAS.EVENT_COMPETITIVE_BALLROOM_ENTRY ECBE
JOIN DAS.EVENT_COMPETITIVE_BALLROOM ECB ON ECBE.COMPETITIVE_BALLROOM_EVENT_ID = ECB.ID
JOIN DAS.EVENT E ON ECB.EVENT_ID = E.ID
WHERE ECBE.PARTNERSHIP_ID = 2
AND E.COMPETITION_ID = 8