// Code generated by MockGen. DO NOT EDIT.
// Source: ./businesslogic/athlete_competition_entry.go

// Package mock_businesslogic is a generated GoMock package.
package mock_businesslogic

import (
	businesslogic "github.com/DancesportSoftware/das/businesslogic"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIAthleteCompetitionEntryRepository is a mock of IAthleteCompetitionEntryRepository interface
type MockIAthleteCompetitionEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAthleteCompetitionEntryRepositoryMockRecorder
}

// MockIAthleteCompetitionEntryRepositoryMockRecorder is the mock recorder for MockIAthleteCompetitionEntryRepository
type MockIAthleteCompetitionEntryRepositoryMockRecorder struct {
	mock *MockIAthleteCompetitionEntryRepository
}

// NewMockIAthleteCompetitionEntryRepository creates a new mock instance
func NewMockIAthleteCompetitionEntryRepository(ctrl *gomock.Controller) *MockIAthleteCompetitionEntryRepository {
	mock := &MockIAthleteCompetitionEntryRepository{ctrl: ctrl}
	mock.recorder = &MockIAthleteCompetitionEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAthleteCompetitionEntryRepository) EXPECT() *MockIAthleteCompetitionEntryRepositoryMockRecorder {
	return m.recorder
}

// CreateEntry mocks base method
func (m *MockIAthleteCompetitionEntryRepository) CreateEntry(entry *businesslogic.AthleteCompetitionEntry) error {
	ret := m.ctrl.Call(m, "CreateEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEntry indicates an expected call of CreateEntry
func (mr *MockIAthleteCompetitionEntryRepositoryMockRecorder) CreateEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockIAthleteCompetitionEntryRepository)(nil).CreateEntry), entry)
}

// DeleteEntry mocks base method
func (m *MockIAthleteCompetitionEntryRepository) DeleteEntry(entry businesslogic.AthleteCompetitionEntry) error {
	ret := m.ctrl.Call(m, "DeleteEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry
func (mr *MockIAthleteCompetitionEntryRepositoryMockRecorder) DeleteEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockIAthleteCompetitionEntryRepository)(nil).DeleteEntry), entry)
}

// SearchEntry mocks base method
func (m *MockIAthleteCompetitionEntryRepository) SearchEntry(criteria businesslogic.SearchAthleteCompetitionEntryCriteria) ([]businesslogic.AthleteCompetitionEntry, error) {
	ret := m.ctrl.Call(m, "SearchEntry", criteria)
	ret0, _ := ret[0].([]businesslogic.AthleteCompetitionEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEntry indicates an expected call of SearchEntry
func (mr *MockIAthleteCompetitionEntryRepositoryMockRecorder) SearchEntry(criteria interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEntry", reflect.TypeOf((*MockIAthleteCompetitionEntryRepository)(nil).SearchEntry), criteria)
}

// UpdateEntry mocks base method
func (m *MockIAthleteCompetitionEntryRepository) UpdateEntry(entry businesslogic.AthleteCompetitionEntry) error {
	ret := m.ctrl.Call(m, "UpdateEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEntry indicates an expected call of UpdateEntry
func (mr *MockIAthleteCompetitionEntryRepositoryMockRecorder) UpdateEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockIAthleteCompetitionEntryRepository)(nil).UpdateEntry), entry)
}
