// Code generated by MockGen. DO NOT EDIT.
// Source: ./businesslogic/competitionentry.go

// Package mock_businesslogic is a generated GoMock package.
package mock_businesslogic

import (
	businesslogic "github.com/DancesportSoftware/das/businesslogic"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIAthleteCompetitionEntryRepository is a mock of IAthleteCompetitionEntryRepository interface
type MockIAthleteCompetitionEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAthleteCompetitionEntryRepositoryMockRecorder
}

// MockIAthleteCompetitionEntryRepositoryMockRecorder is the mock recorder for MockIAthleteCompetitionEntryRepository
type MockIAthleteCompetitionEntryRepositoryMockRecorder struct {
	mock *MockIAthleteCompetitionEntryRepository
}

// NewMockIAthleteCompetitionEntryRepository creates a new mock instance
func NewMockIAthleteCompetitionEntryRepository(ctrl *gomock.Controller) *MockIAthleteCompetitionEntryRepository {
	mock := &MockIAthleteCompetitionEntryRepository{ctrl: ctrl}
	mock.recorder = &MockIAthleteCompetitionEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAthleteCompetitionEntryRepository) EXPECT() *MockIAthleteCompetitionEntryRepositoryMockRecorder {
	return m.recorder
}

// CreateEntry mocks base method
func (m *MockIAthleteCompetitionEntryRepository) CreateEntry(entry *businesslogic.AthleteCompetitionEntry) error {
	ret := m.ctrl.Call(m, "CreateEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEntry indicates an expected call of CreateEntry
func (mr *MockIAthleteCompetitionEntryRepositoryMockRecorder) CreateEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockIAthleteCompetitionEntryRepository)(nil).CreateEntry), entry)
}

// DeleteEntry mocks base method
func (m *MockIAthleteCompetitionEntryRepository) DeleteEntry(entry businesslogic.AthleteCompetitionEntry) error {
	ret := m.ctrl.Call(m, "DeleteEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry
func (mr *MockIAthleteCompetitionEntryRepositoryMockRecorder) DeleteEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockIAthleteCompetitionEntryRepository)(nil).DeleteEntry), entry)
}

// SearchEntry mocks base method
func (m *MockIAthleteCompetitionEntryRepository) SearchEntry(criteria businesslogic.SearchAthleteCompetitionEntryCriteria) ([]businesslogic.AthleteCompetitionEntry, error) {
	ret := m.ctrl.Call(m, "SearchEntry", criteria)
	ret0, _ := ret[0].([]businesslogic.AthleteCompetitionEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEntry indicates an expected call of SearchEntry
func (mr *MockIAthleteCompetitionEntryRepositoryMockRecorder) SearchEntry(criteria interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEntry", reflect.TypeOf((*MockIAthleteCompetitionEntryRepository)(nil).SearchEntry), criteria)
}

// UpdateEntry mocks base method
func (m *MockIAthleteCompetitionEntryRepository) UpdateEntry(entry businesslogic.AthleteCompetitionEntry) error {
	ret := m.ctrl.Call(m, "UpdateEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEntry indicates an expected call of UpdateEntry
func (mr *MockIAthleteCompetitionEntryRepositoryMockRecorder) UpdateEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockIAthleteCompetitionEntryRepository)(nil).UpdateEntry), entry)
}

// MockIPartnershipCompetitionEntryRepository is a mock of IPartnershipCompetitionEntryRepository interface
type MockIPartnershipCompetitionEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPartnershipCompetitionEntryRepositoryMockRecorder
}

// MockIPartnershipCompetitionEntryRepositoryMockRecorder is the mock recorder for MockIPartnershipCompetitionEntryRepository
type MockIPartnershipCompetitionEntryRepositoryMockRecorder struct {
	mock *MockIPartnershipCompetitionEntryRepository
}

// NewMockIPartnershipCompetitionEntryRepository creates a new mock instance
func NewMockIPartnershipCompetitionEntryRepository(ctrl *gomock.Controller) *MockIPartnershipCompetitionEntryRepository {
	mock := &MockIPartnershipCompetitionEntryRepository{ctrl: ctrl}
	mock.recorder = &MockIPartnershipCompetitionEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPartnershipCompetitionEntryRepository) EXPECT() *MockIPartnershipCompetitionEntryRepositoryMockRecorder {
	return m.recorder
}

// CreateEntry mocks base method
func (m *MockIPartnershipCompetitionEntryRepository) CreateEntry(entry *businesslogic.PartnershipCompetitionEntry) error {
	ret := m.ctrl.Call(m, "CreateEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEntry indicates an expected call of CreateEntry
func (mr *MockIPartnershipCompetitionEntryRepositoryMockRecorder) CreateEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockIPartnershipCompetitionEntryRepository)(nil).CreateEntry), entry)
}

// DeleteEntry mocks base method
func (m *MockIPartnershipCompetitionEntryRepository) DeleteEntry(entry businesslogic.PartnershipCompetitionEntry) error {
	ret := m.ctrl.Call(m, "DeleteEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry
func (mr *MockIPartnershipCompetitionEntryRepositoryMockRecorder) DeleteEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockIPartnershipCompetitionEntryRepository)(nil).DeleteEntry), entry)
}

// SearchEntry mocks base method
func (m *MockIPartnershipCompetitionEntryRepository) SearchEntry(criteria businesslogic.SearchPartnershipCompetitionEntryCriteria) ([]businesslogic.PartnershipCompetitionEntry, error) {
	ret := m.ctrl.Call(m, "SearchEntry", criteria)
	ret0, _ := ret[0].([]businesslogic.PartnershipCompetitionEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEntry indicates an expected call of SearchEntry
func (mr *MockIPartnershipCompetitionEntryRepositoryMockRecorder) SearchEntry(criteria interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEntry", reflect.TypeOf((*MockIPartnershipCompetitionEntryRepository)(nil).SearchEntry), criteria)
}

// UpdateEntry mocks base method
func (m *MockIPartnershipCompetitionEntryRepository) UpdateEntry(entry businesslogic.PartnershipCompetitionEntry) error {
	ret := m.ctrl.Call(m, "UpdateEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEntry indicates an expected call of UpdateEntry
func (mr *MockIPartnershipCompetitionEntryRepositoryMockRecorder) UpdateEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockIPartnershipCompetitionEntryRepository)(nil).UpdateEntry), entry)
}

// MockIAdjudicatorCompetitionEntryRepository is a mock of IAdjudicatorCompetitionEntryRepository interface
type MockIAdjudicatorCompetitionEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAdjudicatorCompetitionEntryRepositoryMockRecorder
}

// MockIAdjudicatorCompetitionEntryRepositoryMockRecorder is the mock recorder for MockIAdjudicatorCompetitionEntryRepository
type MockIAdjudicatorCompetitionEntryRepositoryMockRecorder struct {
	mock *MockIAdjudicatorCompetitionEntryRepository
}

// NewMockIAdjudicatorCompetitionEntryRepository creates a new mock instance
func NewMockIAdjudicatorCompetitionEntryRepository(ctrl *gomock.Controller) *MockIAdjudicatorCompetitionEntryRepository {
	mock := &MockIAdjudicatorCompetitionEntryRepository{ctrl: ctrl}
	mock.recorder = &MockIAdjudicatorCompetitionEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAdjudicatorCompetitionEntryRepository) EXPECT() *MockIAdjudicatorCompetitionEntryRepositoryMockRecorder {
	return m.recorder
}

// CreateEntry mocks base method
func (m *MockIAdjudicatorCompetitionEntryRepository) CreateEntry(entry *businesslogic.AdjudicatorCompetitionEntry) error {
	ret := m.ctrl.Call(m, "CreateEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEntry indicates an expected call of CreateEntry
func (mr *MockIAdjudicatorCompetitionEntryRepositoryMockRecorder) CreateEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockIAdjudicatorCompetitionEntryRepository)(nil).CreateEntry), entry)
}

// DeleteEntry mocks base method
func (m *MockIAdjudicatorCompetitionEntryRepository) DeleteEntry(entry businesslogic.AdjudicatorCompetitionEntry) error {
	ret := m.ctrl.Call(m, "DeleteEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry
func (mr *MockIAdjudicatorCompetitionEntryRepositoryMockRecorder) DeleteEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockIAdjudicatorCompetitionEntryRepository)(nil).DeleteEntry), entry)
}

// SearchEntry mocks base method
func (m *MockIAdjudicatorCompetitionEntryRepository) SearchEntry(criteria businesslogic.SearchAdjudicatorCompetitionEntryCriteria) ([]businesslogic.AdjudicatorCompetitionEntry, error) {
	ret := m.ctrl.Call(m, "SearchEntry", criteria)
	ret0, _ := ret[0].([]businesslogic.AdjudicatorCompetitionEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEntry indicates an expected call of SearchEntry
func (mr *MockIAdjudicatorCompetitionEntryRepositoryMockRecorder) SearchEntry(criteria interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEntry", reflect.TypeOf((*MockIAdjudicatorCompetitionEntryRepository)(nil).SearchEntry), criteria)
}

// UpdateEntry mocks base method
func (m *MockIAdjudicatorCompetitionEntryRepository) UpdateEntry(entry businesslogic.AdjudicatorCompetitionEntry) error {
	ret := m.ctrl.Call(m, "UpdateEntry", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEntry indicates an expected call of UpdateEntry
func (mr *MockIAdjudicatorCompetitionEntryRepositoryMockRecorder) UpdateEntry(entry interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockIAdjudicatorCompetitionEntryRepository)(nil).UpdateEntry), entry)
}

// MockIScrutineerCompetitionEntryRepository is a mock of IScrutineerCompetitionEntryRepository interface
type MockIScrutineerCompetitionEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIScrutineerCompetitionEntryRepositoryMockRecorder
}

// MockIScrutineerCompetitionEntryRepositoryMockRecorder is the mock recorder for MockIScrutineerCompetitionEntryRepository
type MockIScrutineerCompetitionEntryRepositoryMockRecorder struct {
	mock *MockIScrutineerCompetitionEntryRepository
}

// NewMockIScrutineerCompetitionEntryRepository creates a new mock instance
func NewMockIScrutineerCompetitionEntryRepository(ctrl *gomock.Controller) *MockIScrutineerCompetitionEntryRepository {
	mock := &MockIScrutineerCompetitionEntryRepository{ctrl: ctrl}
	mock.recorder = &MockIScrutineerCompetitionEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIScrutineerCompetitionEntryRepository) EXPECT() *MockIScrutineerCompetitionEntryRepositoryMockRecorder {
	return m.recorder
}

// CreateEntry mocks base method
func (m *MockIScrutineerCompetitionEntryRepository) CreateEntry() {
	m.ctrl.Call(m, "CreateEntry")
}

// CreateEntry indicates an expected call of CreateEntry
func (mr *MockIScrutineerCompetitionEntryRepositoryMockRecorder) CreateEntry() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntry", reflect.TypeOf((*MockIScrutineerCompetitionEntryRepository)(nil).CreateEntry))
}
