// Code generated by MockGen. DO NOT EDIT.
// Source: ./businesslogic/partnership.go

// Package mock_businesslogic is a generated GoMock package.
package mock_businesslogic

import (
	businesslogic "github.com/DancesportSoftware/das/businesslogic"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIPartnershipRoleRepository is a mock of IPartnershipRoleRepository interface
type MockIPartnershipRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPartnershipRoleRepositoryMockRecorder
}

// MockIPartnershipRoleRepositoryMockRecorder is the mock recorder for MockIPartnershipRoleRepository
type MockIPartnershipRoleRepositoryMockRecorder struct {
	mock *MockIPartnershipRoleRepository
}

// NewMockIPartnershipRoleRepository creates a new mock instance
func NewMockIPartnershipRoleRepository(ctrl *gomock.Controller) *MockIPartnershipRoleRepository {
	mock := &MockIPartnershipRoleRepository{ctrl: ctrl}
	mock.recorder = &MockIPartnershipRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPartnershipRoleRepository) EXPECT() *MockIPartnershipRoleRepositoryMockRecorder {
	return m.recorder
}

// GetAllPartnershipRoles mocks base method
func (m *MockIPartnershipRoleRepository) GetAllPartnershipRoles() ([]businesslogic.PartnershipRole, error) {
	ret := m.ctrl.Call(m, "GetAllPartnershipRoles")
	ret0, _ := ret[0].([]businesslogic.PartnershipRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPartnershipRoles indicates an expected call of GetAllPartnershipRoles
func (mr *MockIPartnershipRoleRepositoryMockRecorder) GetAllPartnershipRoles() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPartnershipRoles", reflect.TypeOf((*MockIPartnershipRoleRepository)(nil).GetAllPartnershipRoles))
}

// MockIPartnershipStatusRepository is a mock of IPartnershipStatusRepository interface
type MockIPartnershipStatusRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPartnershipStatusRepositoryMockRecorder
}

// MockIPartnershipStatusRepositoryMockRecorder is the mock recorder for MockIPartnershipStatusRepository
type MockIPartnershipStatusRepositoryMockRecorder struct {
	mock *MockIPartnershipStatusRepository
}

// NewMockIPartnershipStatusRepository creates a new mock instance
func NewMockIPartnershipStatusRepository(ctrl *gomock.Controller) *MockIPartnershipStatusRepository {
	mock := &MockIPartnershipStatusRepository{ctrl: ctrl}
	mock.recorder = &MockIPartnershipStatusRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPartnershipStatusRepository) EXPECT() *MockIPartnershipStatusRepositoryMockRecorder {
	return m.recorder
}

// GetAllPartnershipStatus mocks base method
func (m *MockIPartnershipStatusRepository) GetAllPartnershipStatus() ([]businesslogic.PartnershipStatus, error) {
	ret := m.ctrl.Call(m, "GetAllPartnershipStatus")
	ret0, _ := ret[0].([]businesslogic.PartnershipStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPartnershipStatus indicates an expected call of GetAllPartnershipStatus
func (mr *MockIPartnershipStatusRepositoryMockRecorder) GetAllPartnershipStatus() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPartnershipStatus", reflect.TypeOf((*MockIPartnershipStatusRepository)(nil).GetAllPartnershipStatus))
}

// MockIPartnershipRepository is a mock of IPartnershipRepository interface
type MockIPartnershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPartnershipRepositoryMockRecorder
}

// MockIPartnershipRepositoryMockRecorder is the mock recorder for MockIPartnershipRepository
type MockIPartnershipRepositoryMockRecorder struct {
	mock *MockIPartnershipRepository
}

// NewMockIPartnershipRepository creates a new mock instance
func NewMockIPartnershipRepository(ctrl *gomock.Controller) *MockIPartnershipRepository {
	mock := &MockIPartnershipRepository{ctrl: ctrl}
	mock.recorder = &MockIPartnershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPartnershipRepository) EXPECT() *MockIPartnershipRepositoryMockRecorder {
	return m.recorder
}

// CreatePartnership mocks base method
func (m *MockIPartnershipRepository) CreatePartnership(partnership *businesslogic.Partnership) error {
	ret := m.ctrl.Call(m, "CreatePartnership", partnership)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePartnership indicates an expected call of CreatePartnership
func (mr *MockIPartnershipRepositoryMockRecorder) CreatePartnership(partnership interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePartnership", reflect.TypeOf((*MockIPartnershipRepository)(nil).CreatePartnership), partnership)
}

// SearchPartnership mocks base method
func (m *MockIPartnershipRepository) SearchPartnership(criteria businesslogic.SearchPartnershipCriteria) ([]businesslogic.Partnership, error) {
	ret := m.ctrl.Call(m, "SearchPartnership", criteria)
	ret0, _ := ret[0].([]businesslogic.Partnership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPartnership indicates an expected call of SearchPartnership
func (mr *MockIPartnershipRepositoryMockRecorder) SearchPartnership(criteria interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPartnership", reflect.TypeOf((*MockIPartnershipRepository)(nil).SearchPartnership), criteria)
}

// UpdatePartnership mocks base method
func (m *MockIPartnershipRepository) UpdatePartnership(partnership businesslogic.Partnership) error {
	ret := m.ctrl.Call(m, "UpdatePartnership", partnership)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePartnership indicates an expected call of UpdatePartnership
func (mr *MockIPartnershipRepositoryMockRecorder) UpdatePartnership(partnership interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePartnership", reflect.TypeOf((*MockIPartnershipRepository)(nil).UpdatePartnership), partnership)
}

// DeletePartnership mocks base method
func (m *MockIPartnershipRepository) DeletePartnership(partnership businesslogic.Partnership) error {
	ret := m.ctrl.Call(m, "DeletePartnership", partnership)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePartnership indicates an expected call of DeletePartnership
func (mr *MockIPartnershipRepositoryMockRecorder) DeletePartnership(partnership interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePartnership", reflect.TypeOf((*MockIPartnershipRepository)(nil).DeletePartnership), partnership)
}
