// Code generated by MockGen. DO NOT EDIT.
// Source: ./businesslogic/partnershiprequest.go

// Package mock_businesslogic is a generated GoMock package.
package mock_businesslogic

import (
	businesslogic "github.com/DancesportSoftware/das/businesslogic"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIPartnershipRequestRepository is a mock of IPartnershipRequestRepository interface
type MockIPartnershipRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPartnershipRequestRepositoryMockRecorder
}

// MockIPartnershipRequestRepositoryMockRecorder is the mock recorder for MockIPartnershipRequestRepository
type MockIPartnershipRequestRepositoryMockRecorder struct {
	mock *MockIPartnershipRequestRepository
}

// NewMockIPartnershipRequestRepository creates a new mock instance
func NewMockIPartnershipRequestRepository(ctrl *gomock.Controller) *MockIPartnershipRequestRepository {
	mock := &MockIPartnershipRequestRepository{ctrl: ctrl}
	mock.recorder = &MockIPartnershipRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIPartnershipRequestRepository) EXPECT() *MockIPartnershipRequestRepositoryMockRecorder {
	return m.recorder
}

// CreatePartnershipRequest mocks base method
func (m *MockIPartnershipRequestRepository) CreatePartnershipRequest(request *businesslogic.PartnershipRequest) error {
	ret := m.ctrl.Call(m, "CreatePartnershipRequest", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePartnershipRequest indicates an expected call of CreatePartnershipRequest
func (mr *MockIPartnershipRequestRepositoryMockRecorder) CreatePartnershipRequest(request interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePartnershipRequest", reflect.TypeOf((*MockIPartnershipRequestRepository)(nil).CreatePartnershipRequest), request)
}

// SearchPartnershipRequest mocks base method
func (m *MockIPartnershipRequestRepository) SearchPartnershipRequest(criteria businesslogic.SearchPartnershipRequestCriteria) ([]businesslogic.PartnershipRequest, error) {
	ret := m.ctrl.Call(m, "SearchPartnershipRequest", criteria)
	ret0, _ := ret[0].([]businesslogic.PartnershipRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPartnershipRequest indicates an expected call of SearchPartnershipRequest
func (mr *MockIPartnershipRequestRepositoryMockRecorder) SearchPartnershipRequest(criteria interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPartnershipRequest", reflect.TypeOf((*MockIPartnershipRequestRepository)(nil).SearchPartnershipRequest), criteria)
}

// DeletePartnershipRequest mocks base method
func (m *MockIPartnershipRequestRepository) DeletePartnershipRequest(request businesslogic.PartnershipRequest) error {
	ret := m.ctrl.Call(m, "DeletePartnershipRequest", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePartnershipRequest indicates an expected call of DeletePartnershipRequest
func (mr *MockIPartnershipRequestRepositoryMockRecorder) DeletePartnershipRequest(request interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePartnershipRequest", reflect.TypeOf((*MockIPartnershipRequestRepository)(nil).DeletePartnershipRequest), request)
}

// UpdatePartnershipRequest mocks base method
func (m *MockIPartnershipRequestRepository) UpdatePartnershipRequest(request businesslogic.PartnershipRequest) error {
	ret := m.ctrl.Call(m, "UpdatePartnershipRequest", request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePartnershipRequest indicates an expected call of UpdatePartnershipRequest
func (mr *MockIPartnershipRequestRepositoryMockRecorder) UpdatePartnershipRequest(request interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePartnershipRequest", reflect.TypeOf((*MockIPartnershipRequestRepository)(nil).UpdatePartnershipRequest), request)
}
