// Code generated by MockGen. DO NOT EDIT.
// Source: ./businesslogic/provision.go

// Package mock_businesslogic is a generated GoMock package.
package mock_businesslogic

import (
	businesslogic "github.com/DancesportSoftware/das/businesslogic"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIRoleApplicationRepository is a mock of IRoleApplicationRepository interface
type MockIRoleApplicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRoleApplicationRepositoryMockRecorder
}

// MockIRoleApplicationRepositoryMockRecorder is the mock recorder for MockIRoleApplicationRepository
type MockIRoleApplicationRepositoryMockRecorder struct {
	mock *MockIRoleApplicationRepository
}

// NewMockIRoleApplicationRepository creates a new mock instance
func NewMockIRoleApplicationRepository(ctrl *gomock.Controller) *MockIRoleApplicationRepository {
	mock := &MockIRoleApplicationRepository{ctrl: ctrl}
	mock.recorder = &MockIRoleApplicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIRoleApplicationRepository) EXPECT() *MockIRoleApplicationRepositoryMockRecorder {
	return m.recorder
}

// CreateApplication mocks base method
func (m *MockIRoleApplicationRepository) CreateApplication(application *businesslogic.RoleApplication) error {
	ret := m.ctrl.Call(m, "CreateApplication", application)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApplication indicates an expected call of CreateApplication
func (mr *MockIRoleApplicationRepositoryMockRecorder) CreateApplication(application interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockIRoleApplicationRepository)(nil).CreateApplication), application)
}

// SearchApplication mocks base method
func (m *MockIRoleApplicationRepository) SearchApplication(criteria businesslogic.SearchRoleApplicationCriteria) ([]businesslogic.RoleApplication, error) {
	ret := m.ctrl.Call(m, "SearchApplication", criteria)
	ret0, _ := ret[0].([]businesslogic.RoleApplication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchApplication indicates an expected call of SearchApplication
func (mr *MockIRoleApplicationRepositoryMockRecorder) SearchApplication(criteria interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchApplication", reflect.TypeOf((*MockIRoleApplicationRepository)(nil).SearchApplication), criteria)
}

// UpdateApplication mocks base method
func (m *MockIRoleApplicationRepository) UpdateApplication(application businesslogic.RoleApplication) error {
	ret := m.ctrl.Call(m, "UpdateApplication", application)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateApplication indicates an expected call of UpdateApplication
func (mr *MockIRoleApplicationRepositoryMockRecorder) UpdateApplication(application interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApplication", reflect.TypeOf((*MockIRoleApplicationRepository)(nil).UpdateApplication), application)
}

// MockIOrganizerProvisionRepository is a mock of IOrganizerProvisionRepository interface
type MockIOrganizerProvisionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOrganizerProvisionRepositoryMockRecorder
}

// MockIOrganizerProvisionRepositoryMockRecorder is the mock recorder for MockIOrganizerProvisionRepository
type MockIOrganizerProvisionRepositoryMockRecorder struct {
	mock *MockIOrganizerProvisionRepository
}

// NewMockIOrganizerProvisionRepository creates a new mock instance
func NewMockIOrganizerProvisionRepository(ctrl *gomock.Controller) *MockIOrganizerProvisionRepository {
	mock := &MockIOrganizerProvisionRepository{ctrl: ctrl}
	mock.recorder = &MockIOrganizerProvisionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIOrganizerProvisionRepository) EXPECT() *MockIOrganizerProvisionRepositoryMockRecorder {
	return m.recorder
}

// CreateOrganizerProvision mocks base method
func (m *MockIOrganizerProvisionRepository) CreateOrganizerProvision(provision *businesslogic.OrganizerProvision) error {
	ret := m.ctrl.Call(m, "CreateOrganizerProvision", provision)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrganizerProvision indicates an expected call of CreateOrganizerProvision
func (mr *MockIOrganizerProvisionRepositoryMockRecorder) CreateOrganizerProvision(provision interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganizerProvision", reflect.TypeOf((*MockIOrganizerProvisionRepository)(nil).CreateOrganizerProvision), provision)
}

// UpdateOrganizerProvision mocks base method
func (m *MockIOrganizerProvisionRepository) UpdateOrganizerProvision(provision businesslogic.OrganizerProvision) error {
	ret := m.ctrl.Call(m, "UpdateOrganizerProvision", provision)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrganizerProvision indicates an expected call of UpdateOrganizerProvision
func (mr *MockIOrganizerProvisionRepositoryMockRecorder) UpdateOrganizerProvision(provision interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizerProvision", reflect.TypeOf((*MockIOrganizerProvisionRepository)(nil).UpdateOrganizerProvision), provision)
}

// DeleteOrganizerProvision mocks base method
func (m *MockIOrganizerProvisionRepository) DeleteOrganizerProvision(provision businesslogic.OrganizerProvision) error {
	ret := m.ctrl.Call(m, "DeleteOrganizerProvision", provision)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganizerProvision indicates an expected call of DeleteOrganizerProvision
func (mr *MockIOrganizerProvisionRepositoryMockRecorder) DeleteOrganizerProvision(provision interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganizerProvision", reflect.TypeOf((*MockIOrganizerProvisionRepository)(nil).DeleteOrganizerProvision), provision)
}

// SearchOrganizerProvision mocks base method
func (m *MockIOrganizerProvisionRepository) SearchOrganizerProvision(criteria businesslogic.SearchOrganizerProvisionCriteria) ([]businesslogic.OrganizerProvision, error) {
	ret := m.ctrl.Call(m, "SearchOrganizerProvision", criteria)
	ret0, _ := ret[0].([]businesslogic.OrganizerProvision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchOrganizerProvision indicates an expected call of SearchOrganizerProvision
func (mr *MockIOrganizerProvisionRepositoryMockRecorder) SearchOrganizerProvision(criteria interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchOrganizerProvision", reflect.TypeOf((*MockIOrganizerProvisionRepository)(nil).SearchOrganizerProvision), criteria)
}
