CREATE TABLE IF NOT EXISTS APPLICATION.ANNOUNCEMENT (
  ID SERIAL NOT NULL  PRIMARY KEY ,
  TITLE VARCHAR(80) NOT NULL,
  CATEGORY_ID INTEGER NOT NULL REFERENCES APPLICATION.ANNOUNCEMENT_CATEGORY(ID),
  MESSAGE TEXT NOT NULL,
  EFFECTIVE_START TIMESTAMP NOT NULL DEFAULT NOW(),
  EFFECTIVE_END TIMESTAMP NOT NULL DEFAULT NOW(),
  CREATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATE_USER_ID INTEGER NOT NULL REFERENCES DAS.ACCOUNT(ID),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

-- create indexes
CREATE INDEX IF NOT EXISTS title_idx ON APPLICATION.ANNOUNCEMENT(TITLE);
CREATE INDEX IF NOT EXISTS category_idx ON APPLICATION.ANNOUNCEMENT(CATEGORY_ID);
CREATE INDEX IF NOT EXISTS eff_start_idx ON APPLICATION.ANNOUNCEMENT(EFFECTIVE_START);
CREATE INDEX IF NOT EXISTS eff_end_idx ON APPLICATION.ANNOUNCEMENT(EFFECTIVE_END);