CREATE TABLE IF NOT EXISTS APPLICATION.VERSION (
  ID SERIAL NOT NULL  PRIMARY KEY ,
  MAJOR_VERSION INTEGER NOT NULL,
  MINOR_VERSION INTEGER NOT NULL,
  FIX_VERSION INTEGER NOT NULL,
  BUILD_VERSION INTEGER NOT NULL,
  LAST_BUILD TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CURRENT_VERSION BOOLEAN NOT NULL,
  UNIQUE (MAJOR_VERSION, MINOR_VERSION, FIX_VERSION, BUILD_VERSION)
);