CREATE TABLE IF NOT EXISTS APPLICATION.ANNOUNCEMENT_CATEGORY (
  ID SERIAL NOT NULL  PRIMARY KEY ,
  NAME VARCHAR(24) NOT NULL UNIQUE,
  DESCRIPTION TEXT,
  DATETIME_CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
  DATETIME_UPDATED TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO APPLICATION.ANNOUNCEMENT_CATEGORY(NAME, DESCRIPTION) VALUES ('Success','Notice for successful maintenance/upgrade/anniversary');
INSERT INTO APPLICATION.ANNOUNCEMENT_CATEGORY(NAME, DESCRIPTION) VALUES ('Info','Notice for site announcement like news/recruitment/opportunities');
INSERT INTO APPLICATION.ANNOUNCEMENT_CATEGORY(NAME, DESCRIPTION) VALUES ('Caution','Notice for upcoming system maintenance');
INSERT INTO APPLICATION.ANNOUNCEMENT_CATEGORY(NAME, DESCRIPTION) VALUES ('Critical','Notice for critical issues like failure/critical issues/shutdown/etc');